/**
 * Industry taxonomy seed (Phase 2 task 2.1): sectors -> categories, India-first.
 * `googleTypes` must be Places API (New) Table A types (checked by db/test/seeds.test.ts against
 * seeds/data/google-place-types-table-a.json). Categories without a matching Google type are
 * discovered through text queries built from `name` + `synonyms` instead.
 * Slugs are stable identifiers used in ResearchSpec `industry.taxonomy_ids`: never rename one.
 */
export interface IndustrySeed {
  slug: string;
  name: string;
  parent?: string;
  synonyms: string[];
  googleTypes: string[];
}

type Category = [slug: string, name: string, googleTypes: string[], synonyms?: string[]];

const SECTORS: { slug: string; name: string; categories: Category[] }[] = [
  {
    slug: 'food-and-beverage',
    name: 'Food & Beverage',
    categories: [
      ['restaurant', 'Restaurant', ['restaurant'], ['eatery', 'dining']],
      ['fine-dining-restaurant', 'Fine Dining Restaurant', ['fine_dining_restaurant']],
      ['family-restaurant', 'Family Restaurant', ['family_restaurant']],
      [
        'north-indian-restaurant',
        'North Indian Restaurant',
        ['north_indian_restaurant'],
        ['punjabi restaurant', 'mughlai'],
      ],
      [
        'south-indian-restaurant',
        'South Indian Restaurant',
        ['south_indian_restaurant'],
        ['udupi', 'dosa corner', 'tiffin centre'],
      ],
      ['indian-restaurant', 'Indian Restaurant', ['indian_restaurant']],
      [
        'chinese-restaurant',
        'Chinese Restaurant',
        ['chinese_restaurant'],
        ['indo-chinese', 'chinese corner'],
      ],
      [
        'vegetarian-restaurant',
        'Vegetarian Restaurant',
        ['vegetarian_restaurant'],
        ['pure veg', 'shuddh shakahari'],
      ],
      ['vegan-restaurant', 'Vegan Restaurant', ['vegan_restaurant']],
      ['dhaba', 'Dhaba', ['restaurant'], ['highway dhaba', 'punjabi dhaba']],
      [
        'fast-food-restaurant',
        'Fast Food Restaurant',
        ['fast_food_restaurant'],
        ['quick service restaurant', 'qsr'],
      ],
      [
        'pizza-restaurant',
        'Pizza Restaurant',
        ['pizza_restaurant', 'pizza_delivery'],
        ['pizzeria'],
      ],
      ['burger-restaurant', 'Burger Restaurant', ['hamburger_restaurant']],
      [
        'biryani-restaurant',
        'Biryani Restaurant',
        ['restaurant'],
        ['biryani house', 'biryani point'],
      ],
      ['seafood-restaurant', 'Seafood Restaurant', ['seafood_restaurant'], ['fish restaurant']],
      [
        'barbecue-restaurant',
        'Barbecue & Grill',
        ['barbecue_restaurant', 'bar_and_grill'],
        ['tandoor', 'kebab corner'],
      ],
      ['kebab-shop', 'Kebab & Shawarma Shop', ['kebab_shop', 'shawarma_restaurant']],
      ['cafe', 'Cafe', ['cafe'], ['coffee house']],
      ['coffee-shop', 'Coffee Shop', ['coffee_shop', 'coffee_stand']],
      ['tea-stall', 'Tea Stall', ['tea_house'], ['chai stall', 'chai tapri', 'tea point']],
      ['bakery', 'Bakery', ['bakery'], ['bakers', 'bake house']],
      ['cake-shop', 'Cake Shop', ['cake_shop'], ['cake studio', 'cake point']],
      [
        'sweet-shop',
        'Sweet Shop',
        ['confectionery', 'dessert_shop'],
        ['mithai shop', 'halwai', 'sweets and namkeen'],
      ],
      ['namkeen-snacks-shop', 'Namkeen & Snacks Shop', ['snack_bar'], ['farsan', 'namkeen']],
      ['dessert-shop', 'Dessert Shop', ['dessert_shop', 'dessert_restaurant']],
      ['ice-cream-shop', 'Ice Cream Parlour', ['ice_cream_shop'], ['kulfi', 'gelato']],
      ['juice-shop', 'Juice & Shake Bar', ['juice_shop'], ['juice centre', 'shake bar']],
      ['chocolate-shop', 'Chocolate Shop', ['chocolate_shop']],
      [
        'street-food-stall',
        'Street Food Stall',
        ['snack_bar', 'meal_takeaway'],
        ['chaat corner', 'pani puri', 'vada pav', 'momos'],
      ],
      ['food-court', 'Food Court', ['food_court']],
      ['cloud-kitchen', 'Cloud Kitchen', ['meal_delivery'], ['dark kitchen', 'delivery kitchen']],
      [
        'tiffin-service',
        'Tiffin & Meal Service',
        ['meal_delivery', 'meal_takeaway'],
        ['dabba service', 'mess', 'home food'],
      ],
      [
        'catering-service',
        'Catering Service',
        ['catering_service'],
        ['caterers', 'wedding caterers'],
      ],
      ['bar', 'Bar', ['bar', 'cocktail_bar'], ['lounge']],
      ['pub', 'Pub & Brewpub', ['pub', 'brewpub', 'gastropub'], ['microbrewery']],
      ['lounge', 'Lounge & Hookah Bar', ['lounge_bar', 'hookah_bar']],
      ['night-club', 'Night Club', ['night_club'], ['club', 'discotheque']],
      ['brewery', 'Brewery', ['brewery']],
      ['winery', 'Winery & Vineyard', ['winery', 'vineyard']],
      ['food-delivery', 'Food Delivery', ['food_delivery']],
    ],
  },
  {
    slug: 'retail',
    name: 'Retail',
    categories: [
      [
        'kirana-store',
        'Kirana / General Store',
        ['grocery_store', 'general_store', 'convenience_store'],
        ['kirana', 'general store', 'provision store', 'departmental store'],
      ],
      [
        'supermarket',
        'Supermarket',
        ['supermarket', 'hypermarket', 'discount_supermarket'],
        ['mart'],
      ],
      [
        'fruit-vegetable-shop',
        'Fruit & Vegetable Shop',
        ['market', 'food_store'],
        ['sabzi mandi', 'fruit shop', 'vegetable vendor'],
      ],
      [
        'meat-shop',
        'Meat & Chicken Shop',
        ['butcher_shop'],
        ['chicken shop', 'mutton shop', 'meat market'],
      ],
      ['dairy-shop', 'Dairy & Milk Booth', ['food_store'], ['milk booth', 'dairy', 'doodh dairy']],
      ['organic-store', 'Organic & Health Food Store', ['health_food_store'], ['organic store']],
      [
        'clothing-store',
        'Clothing Store',
        ['clothing_store'],
        ['garment shop', 'readymade garments', 'fashion store'],
      ],
      [
        'womens-clothing-store',
        "Women's Clothing Store",
        ['womens_clothing_store'],
        ['ladies wear', 'kurti shop'],
      ],
      [
        'saree-shop',
        'Saree & Ethnic Wear Shop',
        ['clothing_store'],
        ['saree emporium', 'ethnic wear', 'lehenga shop'],
      ],
      [
        'fabric-shop',
        'Fabric & Textile Shop',
        ['store'],
        ['cloth shop', 'kapda dukan', 'textile shop'],
      ],
      ['tailor', 'Tailor & Boutique', ['tailor'], ['boutique', 'darzi', 'stitching centre']],
      ['footwear-store', 'Footwear Store', ['shoe_store'], ['shoe shop', 'chappal store']],
      [
        'jewellery-store',
        'Jewellery Store',
        ['jewelry_store'],
        ['jewellers', 'sunar', 'gold shop', 'imitation jewellery'],
      ],
      ['watch-store', 'Watch & Accessories Store', ['store'], ['watch shop']],
      [
        'electronics-store',
        'Electronics Store',
        ['electronics_store'],
        ['electronics shop', 'home appliances'],
      ],
      [
        'mobile-phone-store',
        'Mobile Phone Store',
        ['cell_phone_store'],
        ['mobile shop', 'mobile accessories'],
      ],
      [
        'computer-store',
        'Computer & Laptop Store',
        ['electronics_store'],
        ['laptop shop', 'computer shop'],
      ],
      ['hardware-store', 'Hardware Store', ['hardware_store'], ['hardware shop', 'tools shop']],
      ['paint-store', 'Paint Store', ['home_improvement_store'], ['paint shop', 'paint dealer']],
      [
        'sanitaryware-tiles-store',
        'Sanitaryware & Tiles Store',
        ['home_improvement_store', 'building_materials_store'],
        ['tiles showroom', 'bath fittings'],
      ],
      ['furniture-store', 'Furniture Store', ['furniture_store'], ['furniture showroom']],
      [
        'home-decor-store',
        'Home Decor & Furnishing',
        ['home_goods_store'],
        ['furnishing store', 'curtains', 'home decor'],
      ],
      ['mattress-store', 'Mattress Store', ['furniture_store'], ['mattress showroom']],
      ['book-store', 'Book Store', ['book_store'], ['book depot', 'bookshop']],
      [
        'stationery-store',
        'Stationery Store',
        ['store'],
        ['stationery shop', 'xerox and stationery'],
      ],
      ['gift-shop', 'Gift Shop', ['gift_shop'], ['gift gallery', 'novelty store']],
      ['toy-store', 'Toy Store', ['toy_store']],
      ['optical-store', 'Optical Store', ['store'], ['opticians', 'spectacles shop', 'eyewear']],
      [
        'cosmetics-store',
        'Cosmetics & Beauty Store',
        ['cosmetics_store'],
        ['beauty store', 'makeup store'],
      ],
      [
        'pharmacy',
        'Pharmacy / Chemist',
        ['pharmacy', 'drugstore'],
        ['chemist', 'medical store', 'medicals'],
      ],
      [
        'ayurvedic-store',
        'Ayurvedic Store',
        ['pharmacy', 'health_food_store'],
        ['ayurvedic medical', 'herbal store'],
      ],
      [
        'sporting-goods-store',
        'Sporting Goods Store',
        ['sporting_goods_store', 'sportswear_store'],
        ['sports shop'],
      ],
      ['bicycle-store', 'Bicycle Store', ['bicycle_store'], ['cycle shop']],
      ['florist', 'Florist', ['florist'], ['flower shop', 'phool wala']],
      ['liquor-store', 'Liquor Store', ['liquor_store'], ['wine shop', 'theka', 'beer shop']],
      ['department-store', 'Department Store', ['department_store']],
      ['shopping-mall', 'Shopping Mall', ['shopping_mall'], ['mall']],
      [
        'discount-store',
        'Discount & Value Store',
        ['discount_store', 'thrift_store'],
        ['99 store', 'value store'],
      ],
      [
        'pooja-store',
        'Pooja & Religious Items Store',
        ['store'],
        ['pooja samagri', 'religious store'],
      ],
      [
        'handicrafts-store',
        'Handicrafts & Handloom Store',
        ['gift_shop', 'store'],
        ['handloom', 'khadi bhandar', 'emporium'],
      ],
      ['music-instruments-store', 'Musical Instruments Store', ['store'], ['music shop']],
      ['tea-coffee-store', 'Tea & Coffee Store', ['tea_store'], ['tea merchant', 'chai patti']],
      [
        'dry-fruits-store',
        'Dry Fruits & Spices Store',
        ['food_store'],
        ['dry fruit shop', 'masala store', 'spices'],
      ],
      ['bag-luggage-store', 'Bags & Luggage Store', ['store'], ['luggage shop']],
      [
        'gas-station',
        'Petrol Pump',
        ['gas_station'],
        ['petrol pump', 'fuel station', 'cng station'],
      ],
      [
        'farmers-market',
        'Market & Bazaar',
        ['market', 'farmers_market', 'flea_market'],
        ['bazaar', 'haat', 'mandi'],
      ],
    ],
  },
  {
    slug: 'health-care',
    name: 'Health Care',
    categories: [
      [
        'hospital',
        'Hospital',
        ['hospital', 'general_hospital'],
        ['multispeciality hospital', 'nursing home'],
      ],
      ['clinic', 'Clinic', ['medical_clinic', 'medical_center'], ['polyclinic', 'dispensary']],
      ['doctor', 'Doctor / Physician', ['doctor'], ['physician', 'general practitioner', 'mbbs']],
      ['dentist', 'Dental Clinic', ['dental_clinic', 'dentist'], ['dentist', 'dental care']],
      [
        'diagnostic-lab',
        'Diagnostic Lab',
        ['medical_lab'],
        ['pathology lab', 'blood test', 'diagnostic centre'],
      ],
      [
        'imaging-centre',
        'Imaging & Scan Centre',
        ['medical_lab'],
        ['x-ray', 'mri centre', 'ct scan', 'ultrasound'],
      ],
      [
        'physiotherapy-clinic',
        'Physiotherapy Clinic',
        ['physiotherapist'],
        ['physio', 'rehabilitation centre'],
      ],
      ['chiropractor', 'Chiropractor', ['chiropractor']],
      [
        'eye-hospital',
        'Eye Hospital & Clinic',
        ['medical_clinic'],
        ['eye care', 'ophthalmologist'],
      ],
      [
        'skin-clinic',
        'Skin & Hair Clinic',
        ['skin_care_clinic'],
        ['dermatologist', 'hair transplant', 'cosmetology'],
      ],
      [
        'ivf-centre',
        'IVF & Fertility Centre',
        ['medical_clinic'],
        ['fertility clinic', 'test tube baby'],
      ],
      [
        'maternity-hospital',
        'Maternity & Child Hospital',
        ['hospital'],
        ['maternity home', 'children hospital'],
      ],
      [
        'ayurveda-clinic',
        'Ayurveda Clinic',
        ['medical_clinic', 'wellness_center'],
        ['ayurvedic doctor', 'panchakarma'],
      ],
      ['homeopathy-clinic', 'Homeopathy Clinic', ['medical_clinic'], ['homeopath', 'homoeopathic']],
      [
        'mental-health-clinic',
        'Mental Health Clinic',
        ['medical_clinic'],
        ['psychiatrist', 'psychologist', 'counselling'],
      ],
      [
        'de-addiction-centre',
        'Rehabilitation & De-addiction Centre',
        ['medical_center'],
        ['nasha mukti kendra', 'rehab'],
      ],
      ['blood-bank', 'Blood Bank', ['medical_center']],
      [
        'home-healthcare',
        'Home Healthcare & Nursing',
        ['service'],
        ['home nursing', 'caretaker service', 'elder care'],
      ],
      [
        'medical-equipment-supplier',
        'Medical Equipment Supplier',
        ['supplier'],
        ['surgical store', 'medical devices'],
      ],
      ['foot-care', 'Foot Care', ['foot_care'], ['podiatrist']],
      [
        'veterinary-clinic',
        'Veterinary Clinic',
        ['veterinary_care'],
        ['vet', 'animal hospital', 'pet clinic'],
      ],
    ],
  },
  {
    slug: 'beauty-and-wellness',
    name: 'Beauty & Wellness',
    categories: [
      [
        'beauty-salon',
        'Beauty Salon & Parlour',
        ['beauty_salon', 'beautician'],
        ['beauty parlour', 'ladies salon'],
      ],
      ['hair-salon', 'Hair Salon', ['hair_salon', 'hair_care'], ['unisex salon', 'hair studio']],
      ['barber-shop', 'Barber Shop', ['barber_shop'], ['nai', 'gents salon', 'barber']],
      ['nail-salon', 'Nail Salon', ['nail_salon'], ['nail art']],
      ['makeup-artist', 'Makeup Artist', ['makeup_artist'], ['bridal makeup', 'mua']],
      ['mehendi-artist', 'Mehendi Artist', ['body_art_service'], ['mehndi artist', 'henna']],
      ['tattoo-studio', 'Tattoo Studio', ['body_art_service'], ['tattoo parlour']],
      ['spa', 'Spa', ['spa', 'massage_spa'], ['day spa', 'thai spa']],
      ['massage-centre', 'Massage Centre', ['massage'], ['ayurvedic massage']],
      ['wellness-centre', 'Wellness Centre', ['wellness_center'], ['naturopathy']],
      ['tanning-studio', 'Tanning Studio', ['tanning_studio']],
      ['sauna', 'Sauna & Steam', ['sauna', 'public_bath']],
    ],
  },
  {
    slug: 'sports-and-fitness',
    name: 'Sports & Fitness',
    categories: [
      ['gym', 'Gym & Fitness Centre', ['gym', 'fitness_center'], ['fitness studio', 'health club']],
      ['yoga-studio', 'Yoga Studio', ['yoga_studio'], ['yoga classes', 'yoga centre']],
      ['sports-club', 'Sports Club', ['sports_club', 'sports_complex'], ['club house']],
      [
        'sports-academy',
        'Sports Academy & Coaching',
        ['sports_coaching', 'sports_school'],
        ['cricket academy', 'football academy', 'badminton academy'],
      ],
      ['swimming-pool', 'Swimming Pool', ['swimming_pool'], ['swimming classes']],
      [
        'sports-turf',
        'Sports Turf & Arena',
        ['athletic_field', 'sports_activity_location', 'arena'],
        ['box cricket', 'football turf'],
      ],
      [
        'tennis-court',
        'Tennis & Badminton Court',
        ['tennis_court', 'sports_activity_location'],
        ['badminton court'],
      ],
      [
        'martial-arts-school',
        'Martial Arts School',
        ['sports_school'],
        ['karate classes', 'taekwondo'],
      ],
      ['dance-studio', 'Dance Academy', ['dance_hall'], ['dance classes', 'dance school']],
      ['golf-course', 'Golf Course', ['golf_course', 'indoor_golf_course']],
      [
        'adventure-sports',
        'Adventure Sports Centre',
        ['adventure_sports_center', 'off_roading_area'],
        ['trekking', 'paragliding'],
      ],
      [
        'bowling-alley',
        'Bowling & Gaming Zone',
        ['bowling_alley', 'video_arcade', 'amusement_center'],
        ['gaming zone', 'arcade'],
      ],
      ['stadium', 'Stadium', ['stadium']],
    ],
  },
  {
    slug: 'education',
    name: 'Education',
    categories: [
      [
        'school',
        'School',
        ['school', 'primary_school', 'secondary_school'],
        ['public school', 'cbse school', 'icse school', 'vidyalaya'],
      ],
      [
        'preschool',
        'Preschool & Play School',
        ['preschool'],
        ['play school', 'nursery school', 'kindergarten'],
      ],
      ['daycare', 'Daycare & Creche', ['child_care_agency'], ['creche', 'day care']],
      ['college', 'College', ['educational_institution'], ['degree college', 'mahavidyalaya']],
      ['university', 'University', ['university']],
      [
        'coaching-centre',
        'Coaching Centre',
        ['educational_institution'],
        ['coaching institute', 'jee coaching', 'neet coaching', 'upsc coaching', 'classes'],
      ],
      [
        'tuition-centre',
        'Tuition Centre',
        ['educational_institution'],
        ['tuition classes', 'home tuition'],
      ],
      [
        'language-institute',
        'Language & IELTS Institute',
        ['educational_institution'],
        ['ielts coaching', 'spoken english', 'foreign language classes'],
      ],
      [
        'computer-training-institute',
        'Computer Training Institute',
        ['educational_institution'],
        ['computer classes', 'coding classes', 'it training'],
      ],
      [
        'driving-school',
        'Driving School',
        ['educational_institution'],
        ['motor training school', 'driving classes'],
      ],
      [
        'music-school',
        'Music School',
        ['educational_institution'],
        ['music classes', 'music academy'],
      ],
      ['art-school', 'Art & Craft Classes', ['art_studio'], ['drawing classes', 'art classes']],
      [
        'vocational-institute',
        'Vocational Training Institute',
        ['educational_institution'],
        ['iti', 'skill development centre'],
      ],
      [
        'study-abroad-consultant',
        'Study Abroad Consultant',
        ['consultant'],
        ['overseas education', 'education consultant'],
      ],
      ['library', 'Library & Study Centre', ['library'], ['reading room', 'self study centre']],
      ['research-institute', 'Research Institute', ['research_institute']],
    ],
  },
  {
    slug: 'professional-services',
    name: 'Professional Services',
    categories: [
      [
        'chartered-accountant',
        'Chartered Accountant / Accounting Firm',
        ['accounting'],
        ['ca firm', 'tax consultant', 'gst consultant', 'auditor'],
      ],
      ['law-firm', 'Lawyer / Law Firm', ['lawyer'], ['advocate', 'legal services', 'vakil']],
      [
        'company-secretary',
        'Company Secretary & Compliance',
        ['consultant'],
        ['cs firm', 'company registration', 'compliance services'],
      ],
      [
        'business-consultant',
        'Business Consultant',
        ['consultant'],
        ['management consultant', 'business advisory'],
      ],
      [
        'marketing-agency',
        'Marketing & Advertising Agency',
        ['marketing_consultant'],
        ['advertising agency', 'ad agency', 'branding agency'],
      ],
      [
        'digital-marketing-agency',
        'Digital Marketing Agency',
        ['marketing_consultant'],
        ['seo agency', 'social media agency', 'performance marketing'],
      ],
      ['pr-agency', 'PR Agency', ['marketing_consultant'], ['public relations']],
      [
        'recruitment-agency',
        'Recruitment & Staffing Agency',
        ['employment_agency'],
        ['placement agency', 'manpower agency', 'hr consultant'],
      ],
      ['architect', 'Architect', ['consultant'], ['architecture firm']],
      [
        'interior-designer',
        'Interior Designer',
        ['consultant'],
        ['interior design firm', 'interior decorator', 'modular kitchen'],
      ],
      [
        'real-estate-agent',
        'Real Estate Agent',
        ['real_estate_agency'],
        ['property dealer', 'property consultant', 'broker'],
      ],
      [
        'insurance-agent',
        'Insurance Agency',
        ['insurance_agency'],
        ['lic agent', 'insurance advisor'],
      ],
      [
        'financial-advisor',
        'Financial Advisor',
        ['consultant'],
        ['wealth management', 'mutual fund distributor', 'investment advisor'],
      ],
      [
        'event-planner',
        'Event Management Company',
        ['service'],
        ['event management', 'event organiser'],
      ],
      ['wedding-planner', 'Wedding Planner', ['service'], ['wedding management', 'shaadi planner']],
      [
        'photographer',
        'Photographer & Studio',
        ['service'],
        ['photo studio', 'wedding photographer', 'photography'],
      ],
      [
        'video-production',
        'Video Production House',
        ['television_studio'],
        ['film production', 'ad film maker'],
      ],
      [
        'printing-press',
        'Printing Press & Print Shop',
        ['service'],
        ['printers', 'offset printing', 'flex printing', 'xerox'],
      ],
      ['translation-services', 'Translation Services', ['service'], ['translator']],
      [
        'astrologer',
        'Astrologer',
        ['astrologer', 'psychic'],
        ['jyotish', 'vastu consultant', 'numerologist'],
      ],
      ['detective-agency', 'Detective Agency', ['service'], ['private investigator']],
      ['security-agency', 'Security Agency', ['service'], ['security guards', 'security services']],
      [
        'coworking-space',
        'Coworking Space',
        ['coworking_space', 'business_center'],
        ['shared office', 'business centre'],
      ],
      ['corporate-office', 'Corporate Office', ['corporate_office']],
    ],
  },
  {
    slug: 'technology',
    name: 'Technology',
    categories: [
      [
        'software-company',
        'Software Company',
        ['corporate_office'],
        ['software development', 'it company', 'software house'],
      ],
      [
        'saas-company',
        'SaaS Company',
        ['corporate_office'],
        ['saas', 'software as a service', 'b2b software'],
      ],
      [
        'it-services',
        'IT Services & Consulting',
        ['consultant'],
        ['it consulting', 'it solutions', 'managed services'],
      ],
      [
        'web-design-agency',
        'Web Design & Development',
        ['service'],
        ['website design', 'web development company'],
      ],
      ['app-development', 'Mobile App Development', ['service'], ['app developers']],
      [
        'ai-company',
        'AI & Data Company',
        ['corporate_office'],
        ['artificial intelligence', 'machine learning', 'data analytics'],
      ],
      [
        'cybersecurity-company',
        'Cybersecurity Company',
        ['corporate_office'],
        ['information security'],
      ],
      [
        'fintech-company',
        'Fintech Company',
        ['corporate_office'],
        ['payments company', 'fintech startup'],
      ],
      ['edtech-company', 'Edtech Company', ['corporate_office'], ['online learning', 'e-learning']],
      [
        'ecommerce-company',
        'E-commerce Company',
        ['corporate_office'],
        ['online store', 'd2c brand'],
      ],
      [
        'internet-service-provider',
        'Internet Service Provider',
        ['telecommunications_service_provider'],
        ['isp', 'broadband provider', 'wifi provider'],
      ],
      ['telecom-company', 'Telecom Company', ['telecommunications_service_provider']],
      [
        'computer-repair',
        'Computer & Laptop Repair',
        ['electronics_store'],
        ['laptop repair', 'computer service centre'],
      ],
      [
        'mobile-repair',
        'Mobile Repair Shop',
        ['cell_phone_store'],
        ['mobile repairing', 'phone repair'],
      ],
      [
        'cctv-installer',
        'CCTV & Security Systems',
        ['service'],
        ['cctv dealer', 'security systems'],
      ],
      ['cyber-cafe', 'Cyber Cafe', ['internet_cafe'], ['internet cafe', 'csc centre']],
    ],
  },
  {
    slug: 'finance',
    name: 'Finance',
    categories: [
      ['bank', 'Bank', ['bank'], ['bank branch']],
      [
        'nbfc',
        'NBFC & Lending Company',
        ['corporate_office'],
        ['non banking financial company', 'loan company', 'finance company'],
      ],
      ['microfinance', 'Microfinance Institution', ['corporate_office'], ['mfi']],
      [
        'cooperative-bank',
        'Cooperative Bank & Credit Society',
        ['bank'],
        ['credit cooperative', 'sahakari bank'],
      ],
      ['gold-loan', 'Gold Loan Company', ['bank'], ['gold finance']],
      [
        'stock-broker',
        'Stock Broker',
        ['consultant'],
        ['share broker', 'trading company', 'demat'],
      ],
      [
        'loan-agent',
        'Loan Agent / DSA',
        ['consultant'],
        ['loan consultant', 'home loan agent', 'dsa'],
      ],
      ['money-exchange', 'Money Exchange & Remittance', ['service'], ['forex', 'money transfer']],
      [
        'insurance-company',
        'Insurance Company',
        ['insurance_agency'],
        ['general insurance', 'health insurance'],
      ],
    ],
  },
  {
    slug: 'home-services',
    name: 'Home Services',
    categories: [
      ['plumber', 'Plumber', ['plumber'], ['plumbing services']],
      ['electrician', 'Electrician', ['electrician'], ['electrical services', 'wiring']],
      ['painter', 'Painting Contractor', ['painter'], ['house painting', 'painters']],
      ['carpenter', 'Carpenter', ['service'], ['carpentry', 'furniture repair']],
      ['pest-control', 'Pest Control', ['service'], ['termite control', 'fumigation']],
      ['ac-repair', 'AC Repair & Service', ['service'], ['ac service', 'air conditioner repair']],
      [
        'appliance-repair',
        'Home Appliance Repair',
        ['service'],
        ['washing machine repair', 'fridge repair', 'ro service'],
      ],
      [
        'cleaning-service',
        'Cleaning Service',
        ['service'],
        ['deep cleaning', 'housekeeping', 'sofa cleaning'],
      ],
      ['packers-movers', 'Packers & Movers', ['moving_company'], ['movers', 'relocation services']],
      ['locksmith', 'Locksmith', ['locksmith'], ['key maker']],
      ['laundry', 'Laundry & Dry Cleaner', ['laundry'], ['dry cleaners', 'dhobi', 'ironing']],
      [
        'roofing-waterproofing',
        'Roofing & Waterproofing',
        ['roofing_contractor'],
        ['waterproofing contractor'],
      ],
      ['water-purifier-dealer', 'Water Purifier Dealer', ['store'], ['ro dealer', 'water filter']],
      [
        'solar-installer',
        'Solar Installer',
        ['service'],
        ['solar panels', 'rooftop solar', 'solar dealer'],
      ],
      [
        'gardener',
        'Gardening & Landscaping',
        ['garden_center', 'service'],
        ['landscaping', 'mali'],
      ],
      [
        'maid-service',
        'Maid & Domestic Help Agency',
        ['employment_agency'],
        ['maid agency', 'domestic help'],
      ],
    ],
  },
  {
    slug: 'construction-and-real-estate',
    name: 'Construction & Real Estate',
    categories: [
      [
        'builder-developer',
        'Builder & Developer',
        ['corporate_office'],
        ['real estate developer', 'builders', 'construction company'],
      ],
      [
        'civil-contractor',
        'Civil Contractor',
        ['service'],
        ['construction contractor', 'thekedar'],
      ],
      [
        'building-materials',
        'Building Materials Supplier',
        ['building_materials_store', 'supplier'],
        ['cement dealer', 'steel dealer', 'sand supplier', 'bricks'],
      ],
      [
        'glass-aluminium',
        'Glass & Aluminium Work',
        ['service'],
        ['aluminium fabricator', 'glass work'],
      ],
      [
        'fabricator',
        'Steel & Iron Fabricator',
        ['manufacturer'],
        ['welding works', 'grill fabrication'],
      ],
      [
        'modular-kitchen',
        'Modular Kitchen & Wardrobe',
        ['home_improvement_store'],
        ['kitchen showroom'],
      ],
      [
        'apartment-complex',
        'Apartment & Housing Society',
        ['apartment_complex', 'housing_complex', 'condominium_complex'],
        ['society', 'residential complex'],
      ],
      [
        'property-management',
        'Property Management',
        ['real_estate_agency'],
        ['facility management'],
      ],
      ['surveyor', 'Surveyor & Valuer', ['consultant'], ['land surveyor', 'property valuer']],
      ['storage-warehouse', 'Storage & Self Storage', ['storage'], ['self storage', 'godown']],
    ],
  },
  {
    slug: 'automotive',
    name: 'Automotive',
    categories: [
      ['car-dealer', 'Car Dealer & Showroom', ['car_dealer'], ['car showroom', 'used cars']],
      [
        'two-wheeler-dealer',
        'Two-Wheeler Dealer',
        ['car_dealer'],
        ['bike showroom', 'scooter showroom', 'motorcycle dealer'],
      ],
      [
        'ev-dealer',
        'EV Dealer',
        ['car_dealer'],
        ['electric scooter showroom', 'electric vehicle dealer', 'e-rickshaw dealer'],
      ],
      [
        'truck-dealer',
        'Truck & Commercial Vehicle Dealer',
        ['truck_dealer'],
        ['commercial vehicles'],
      ],
      [
        'car-repair',
        'Car Repair & Garage',
        ['car_repair'],
        ['car service centre', 'auto garage', 'mechanic'],
      ],
      [
        'bike-repair',
        'Two-Wheeler Repair',
        ['car_repair'],
        ['bike service', 'motorcycle mechanic'],
      ],
      ['car-wash', 'Car Wash & Detailing', ['car_wash'], ['car spa', 'detailing studio']],
      ['tyre-shop', 'Tyre Shop', ['tire_shop'], ['tyre dealer', 'wheel alignment']],
      ['auto-parts', 'Auto Parts Store', ['auto_parts_store'], ['spare parts', 'car accessories']],
      ['car-rental', 'Car Rental', ['car_rental'], ['self drive cars', 'bike rental']],
      [
        'taxi-service',
        'Taxi & Cab Service',
        ['taxi_service', 'chauffeur_service'],
        ['cab service', 'tours and travels'],
      ],
      [
        'ev-charging',
        'EV Charging Station',
        ['electric_vehicle_charging_station', 'ebike_charging_station'],
      ],
      ['parking', 'Parking', ['parking', 'parking_lot', 'parking_garage']],
    ],
  },
  {
    slug: 'hospitality-and-travel',
    name: 'Hospitality & Travel',
    categories: [
      ['hotel', 'Hotel', ['hotel', 'lodging'], ['lodge', 'budget hotel']],
      ['resort', 'Resort', ['resort_hotel'], ['farmhouse resort']],
      [
        'guest-house',
        'Guest House & Homestay',
        ['guest_house', 'bed_and_breakfast', 'farmstay', 'cottage', 'private_guest_room'],
        ['homestay', 'paying guest', 'pg'],
      ],
      ['hostel', 'Hostel', ['hostel'], ['backpacker hostel', 'boys hostel', 'girls hostel']],
      ['service-apartment', 'Service Apartment', ['extended_stay_hotel'], ['serviced apartments']],
      ['motel', 'Motel & Inn', ['motel', 'inn']],
      [
        'banquet-hall',
        'Banquet Hall',
        ['banquet_hall', 'event_venue'],
        ['marriage hall', 'party hall', 'function hall'],
      ],
      ['wedding-venue', 'Wedding Venue', ['wedding_venue'], ['marriage garden', 'lawn']],
      ['convention-centre', 'Convention Centre', ['convention_center', 'auditorium']],
      [
        'travel-agency',
        'Travel Agency',
        ['travel_agency'],
        ['tours and travels', 'ticket booking', 'visa agent'],
      ],
      ['tour-operator', 'Tour Operator', ['tour_agency'], ['holiday packages', 'pilgrimage tours']],
      ['campsite', 'Campsite', ['campground', 'camping_cabin', 'rv_park']],
      ['tourist-attraction', 'Tourist Attraction', ['tourist_attraction'], ['sightseeing']],
    ],
  },
  {
    slug: 'arts-and-entertainment',
    name: 'Arts & Entertainment',
    categories: [
      ['movie-theatre', 'Cinema', ['movie_theater'], ['multiplex', 'movie hall']],
      [
        'amusement-park',
        'Amusement & Water Park',
        ['amusement_park', 'water_park'],
        ['theme park'],
      ],
      ['event-venue', 'Event Venue', ['event_venue', 'live_music_venue'], ['party venue']],
      ['art-gallery', 'Art Gallery', ['art_gallery', 'art_museum']],
      ['museum', 'Museum', ['museum', 'history_museum']],
      [
        'theatre',
        'Theatre & Performing Arts',
        ['performing_arts_theater', 'amphitheatre', 'opera_house'],
        ['auditorium', 'drama'],
      ],
      ['comedy-club', 'Comedy Club', ['comedy_club']],
      ['karaoke', 'Karaoke', ['karaoke']],
      ['kids-play-area', 'Kids Play Area', ['indoor_playground', 'playground'], ['soft play']],
      [
        'recording-studio',
        'Recording & Music Studio',
        ['service'],
        ['music studio', 'dubbing studio'],
      ],
      ['zoo', 'Zoo & Wildlife Park', ['zoo', 'wildlife_park', 'aquarium']],
      ['casino', 'Casino', ['casino']],
    ],
  },
  {
    slug: 'manufacturing-and-industrial',
    name: 'Manufacturing & Industrial',
    categories: [
      [
        'manufacturer',
        'Manufacturer',
        ['manufacturer'],
        ['factory', 'manufacturing unit', 'industries'],
      ],
      [
        'garment-manufacturer',
        'Garment Manufacturer',
        ['manufacturer'],
        ['apparel manufacturer', 'garment factory'],
      ],
      [
        'textile-mill',
        'Textile Mill',
        ['manufacturer'],
        ['spinning mill', 'weaving', 'power loom'],
      ],
      [
        'food-processing',
        'Food Processing Unit',
        ['manufacturer'],
        ['food manufacturer', 'masala manufacturer', 'packaged food'],
      ],
      [
        'pharma-manufacturer',
        'Pharmaceutical Manufacturer',
        ['manufacturer'],
        ['pharma company', 'drug manufacturer'],
      ],
      [
        'chemical-manufacturer',
        'Chemical Manufacturer',
        ['manufacturer'],
        ['chemical company', 'dyes and chemicals'],
      ],
      [
        'plastic-manufacturer',
        'Plastic & Polymer Manufacturer',
        ['manufacturer'],
        ['plastic products', 'moulding'],
      ],
      [
        'packaging-manufacturer',
        'Packaging Manufacturer',
        ['manufacturer'],
        ['corrugated boxes', 'packaging material'],
      ],
      [
        'machinery-manufacturer',
        'Machinery & Equipment Manufacturer',
        ['manufacturer'],
        ['machine tools', 'industrial machinery'],
      ],
      [
        'electrical-equipment',
        'Electrical Equipment Manufacturer',
        ['manufacturer'],
        ['switchgear', 'cables and wires', 'transformers'],
      ],
      [
        'auto-components',
        'Auto Components Manufacturer',
        ['manufacturer'],
        ['auto parts manufacturer'],
      ],
      ['furniture-manufacturer', 'Furniture Manufacturer', ['manufacturer'], ['furniture factory']],
      ['metal-works', 'Metal Works & Foundry', ['manufacturer'], ['foundry', 'forging', 'casting']],
      [
        'handicrafts-manufacturer',
        'Handicrafts Manufacturer',
        ['manufacturer'],
        ['handicraft exporters'],
      ],
      [
        'cosmetics-manufacturer',
        'Cosmetics Manufacturer',
        ['manufacturer'],
        ['personal care manufacturer', 'third party manufacturing'],
      ],
      ['paper-manufacturer', 'Paper & Printing Products', ['manufacturer'], ['paper mill']],
      [
        'chocolate-factory',
        'Confectionery Manufacturer',
        ['chocolate_factory', 'manufacturer'],
        ['biscuit factory'],
      ],
      [
        'wholesaler',
        'Wholesaler & Distributor',
        ['wholesaler', 'supplier', 'warehouse_store'],
        ['distributor', 'wholesale dealer', 'stockist', 'c&f agent'],
      ],
      ['exporter', 'Exporter & Importer', ['wholesaler'], ['export house', 'importers']],
      [
        'industrial-supplier',
        'Industrial Supplier',
        ['supplier'],
        ['industrial supplies', 'bearings', 'hydraulics'],
      ],
      ['scrap-dealer', 'Scrap Dealer & Recycler', ['supplier'], ['kabadi', 'recycling', 'e-waste']],
    ],
  },
  {
    slug: 'logistics-and-transport',
    name: 'Logistics & Transport',
    categories: [
      [
        'courier-service',
        'Courier Service',
        ['courier_service', 'shipping_service'],
        ['courier', 'parcel service'],
      ],
      [
        'logistics-company',
        'Logistics Company',
        ['transportation_service'],
        ['3pl', 'freight forwarder', 'supply chain'],
      ],
      [
        'transporter',
        'Transporter & Truck Operator',
        ['transportation_service'],
        ['transport company', 'goods carrier', 'truck booking'],
      ],
      ['cold-storage', 'Cold Storage', ['storage'], ['cold chain']],
      ['warehouse', 'Warehouse', ['storage'], ['warehousing', 'godown']],
      ['bus-operator', 'Bus Operator', ['transportation_service'], ['bus service', 'travels']],
      [
        'shipping-company',
        'Shipping & Customs Agent',
        ['shipping_service'],
        ['cha', 'customs clearance'],
      ],
      ['post-office', 'Post Office', ['post_office']],
    ],
  },
  {
    slug: 'agriculture',
    name: 'Agriculture',
    categories: [
      ['farm', 'Farm', ['farm', 'ranch'], ['kisan', 'agricultural farm']],
      ['dairy-farm', 'Dairy Farm', ['farm'], ['gaushala', 'milk dairy']],
      ['poultry-farm', 'Poultry Farm', ['farm'], ['poultry']],
      ['plant-nursery', 'Plant Nursery', ['garden_center'], ['nursery', 'plants shop']],
      [
        'agri-inputs',
        'Seeds, Fertilizer & Pesticides',
        ['store'],
        ['krishi kendra', 'fertilizer shop', 'seed store'],
      ],
      [
        'tractor-dealer',
        'Tractor & Farm Equipment Dealer',
        ['truck_dealer'],
        ['tractor showroom', 'farm machinery'],
      ],
      ['fisheries', 'Fisheries & Aquaculture', ['farm'], ['fish farm']],
    ],
  },
  {
    slug: 'pets',
    name: 'Pets',
    categories: [
      ['pet-store', 'Pet Store', ['pet_store'], ['pet shop', 'pet food']],
      ['pet-grooming', 'Pet Grooming', ['pet_care'], ['dog grooming']],
      [
        'pet-boarding',
        'Pet Boarding & Daycare',
        ['pet_boarding_service'],
        ['dog boarding', 'kennel'],
      ],
      ['pet-cafe', 'Pet Cafe', ['dog_cafe', 'cat_cafe']],
    ],
  },
  {
    slug: 'community-and-government',
    name: 'Community, Religious & Government',
    categories: [
      [
        'ngo',
        'NGO & Non-profit',
        ['non_profit_organization'],
        ['trust', 'foundation', 'charitable society'],
      ],
      [
        'association',
        'Association & Chamber',
        ['association_or_organization'],
        ['trade association', 'chamber of commerce'],
      ],
      ['community-centre', 'Community Centre', ['community_center', 'cultural_center']],
      ['hindu-temple', 'Temple', ['hindu_temple'], ['mandir']],
      ['mosque', 'Mosque', ['mosque'], ['masjid']],
      ['church', 'Church', ['church']],
      ['gurudwara', 'Gurudwara', ['association_or_organization'], ['gurdwara', 'sikh temple']],
      ['buddhist-temple', 'Buddhist Temple', ['buddhist_temple'], ['monastery', 'vihara']],
      [
        'government-office',
        'Government Office',
        ['government_office', 'local_government_office', 'city_hall'],
        ['sarkari daftar', 'municipal office'],
      ],
      ['police-station', 'Police Station', ['police', 'neighborhood_police_station']],
      ['courthouse', 'Court', ['courthouse']],
      ['embassy', 'Embassy & Consulate', ['embassy']],
      [
        'funeral-services',
        'Funeral Services',
        ['funeral_home', 'cemetery'],
        ['crematorium', 'shamshan'],
      ],
    ],
  },
  {
    slug: 'energy-and-utilities',
    name: 'Energy & Utilities',
    categories: [
      [
        'lpg-agency',
        'LPG Gas Agency',
        ['service'],
        ['gas agency', 'indane', 'hp gas', 'bharat gas'],
      ],
      [
        'electrical-contractor',
        'Electrical Contractor',
        ['electrician'],
        ['electrical works', 'electrical contractors'],
      ],
      [
        'water-supplier',
        'Water Supplier',
        ['supplier'],
        ['water tanker', 'mineral water supplier', 'water can'],
      ],
      [
        'renewable-energy',
        'Renewable Energy Company',
        ['corporate_office'],
        ['solar company', 'wind energy'],
      ],
      [
        'generator-dealer',
        'Generator & Inverter Dealer',
        ['store'],
        ['inverter battery', 'genset dealer'],
      ],
    ],
  },
];

export const INDUSTRY_SEEDS: IndustrySeed[] = SECTORS.flatMap((sector) => [
  { slug: sector.slug, name: sector.name, synonyms: [], googleTypes: [] },
  ...sector.categories.map(([slug, name, googleTypes, synonyms = []]): IndustrySeed => ({
    slug,
    name,
    parent: sector.slug,
    synonyms,
    googleTypes,
  })),
]);
