/**
 * Generates TS types + schema constants and Pydantic models from schemas/*.schema.json.
 * Usage: node scripts/gen.ts [--check]   (--check fails if committed output is stale)
 */
import { execFileSync } from 'node:child_process';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';

import { compile, type JSONSchema } from 'json-schema-to-typescript';

const root = resolve(import.meta.dirname, '..');
const schemaDir = join(root, 'schemas');
const tsOut = join(root, 'src', 'generated');
const pyOut = join(root, 'generated', 'python', 'leadforge_contracts');
const check = process.argv.includes('--check');

const HEADER = 'DO NOT EDIT. Generated by packages/contracts/scripts/gen.ts from schemas/.';

/** Base class for generated Pydantic models: serializes to exactly the JSON Schema wire format. */
const WIRE_MODEL_PY = `
from typing import Any

from pydantic import BaseModel, ConfigDict


class WireModel(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    def to_wire(self) -> str:
        """JSON for Redis/HTTP: schema field names (aliases), unset optional fields omitted."""
        return self.model_dump_json(by_alias=True, exclude_unset=True)

    def to_wire_dict(self) -> dict[str, Any]:
        return self.model_dump(mode="json", by_alias=True, exclude_unset=True)
`;

interface SchemaFile {
  base: string; // e.g. job-envelope
  constName: string; // e.g. jobEnvelopeSchema
  moduleName: string; // e.g. job_envelope
  schema: JSONSchema;
}

function camel(base: string): string {
  return base.replace(/-([a-z])/g, (_m, c: string) => c.toUpperCase());
}

function loadSchemas(): SchemaFile[] {
  return readdirSync(schemaDir)
    .filter((f) => f.endsWith('.schema.json'))
    .sort()
    .map((f) => {
      const base = f.replace('.schema.json', '');
      return {
        base,
        constName: `${camel(base)}Schema`,
        moduleName: base.replaceAll('-', '_'),
        schema: JSON.parse(readFileSync(join(schemaDir, f), 'utf8')) as JSONSchema,
      };
    });
}

async function renderTs(files: SchemaFile[]): Promise<Map<string, string>> {
  const out = new Map<string, string>();
  for (const f of files) {
    const ts = await compile(f.schema, f.schema.title ?? f.base, {
      bannerComment: `/* ${HEADER} */`,
      additionalProperties: false,
      unreachableDefinitions: true,
      format: true,
    });
    out.set(`${f.base}.ts`, ts);
  }
  const consts = files
    .map((f) => `export const ${f.constName} = ${JSON.stringify(f.schema, null, 2)} as const;\n`)
    .join('\n');
  out.set('schemas.ts', `/* ${HEADER} */\n\n${consts}`);
  return out;
}

function renderPython(files: SchemaFile[]): Map<string, string> {
  const tmp = mkdtempSync(join(tmpdir(), 'lf-contracts-'));
  try {
    const out = new Map<string, string>();
    for (const f of files) {
      const target = join(tmp, `${f.moduleName}.py`);
      execFileSync(
        'uv',
        [
          'run',
          '--project',
          root,
          '--frozen',
          'datamodel-codegen',
          '--input',
          join(schemaDir, `${f.base}.schema.json`),
          '--input-file-type',
          'jsonschema',
          '--output',
          target,
          '--output-model-type',
          'pydantic_v2.BaseModel',
          '--target-python-version',
          '3.12',
          '--output-datetime-class',
          'AwareDatetime',
          '--use-annotated',
          '--use-standard-collections',
          '--use-union-operator',
          '--field-constraints',
          '--use-schema-description',
          '--use-double-quotes',
          '--enum-field-as-literal',
          'all',
          '--disable-timestamp',
          '--formatters',
          'builtin',
          '--base-class',
          'leadforge_contracts._wire.WireModel',
          '--strict-types',
          'str',
          'int',
          'bool',
          '--collapse-root-models',
          '--custom-file-header',
          `# ${HEADER}`,
        ],
        { stdio: ['ignore', 'ignore', 'inherit'] },
      );
      out.set(`${f.moduleName}.py`, readFileSync(target, 'utf8').replaceAll('\r\n', '\n'));
    }
    const imports = files.map((f) => `from . import ${f.moduleName}`).join('\n');
    const all = files.map((f) => `    "${f.moduleName}",`).join('\n');
    out.set('__init__.py', `# ${HEADER}\n\n${imports}\n\n__all__ = [\n${all}\n]\n`);
    out.set('_wire.py', `# ${HEADER}\n${WIRE_MODEL_PY}`);
    // PEP 561 marker so type checkers use the generated annotations.
    out.set('py.typed', '');
    return out;
  } finally {
    rmSync(tmp, { recursive: true, force: true });
  }
}

function readOrNull(path: string): string | null {
  try {
    return readFileSync(path, 'utf8');
  } catch {
    return null;
  }
}

/** Makes `dir` contain exactly `files` (extra files are removed). Returns stale paths in --check mode. */
function sync(dir: string, files: Map<string, string>): string[] {
  const stale: string[] = [];
  if (!check) mkdirSync(dir, { recursive: true });
  const existing = existsSync(dir)
    ? readdirSync(dir, { withFileTypes: true })
        .filter((e) => e.isFile())
        .map((e) => e.name)
    : [];
  for (const name of existing.filter((n) => !files.has(n))) {
    if (check) stale.push(join(dir, name));
    else rmSync(join(dir, name));
  }
  for (const [name, content] of files) {
    const path = join(dir, name);
    if (readOrNull(path) === content) continue;
    if (check) stale.push(path);
    else writeFileSync(path, content);
  }
  return stale;
}

const schemas = loadSchemas();
const stale = [...sync(tsOut, await renderTs(schemas)), ...sync(pyOut, renderPython(schemas))];
if (check && stale.length > 0) {
  console.error(`Generated contracts are stale. Run "pnpm contracts:gen".\n${stale.join('\n')}`);
  process.exit(1);
}
console.log(check ? 'contracts: generated code is up to date' : 'contracts: generated');
